### ISSUE TITLE
Users can create, read, update, and delete a profile in the database

### ISSUE THREAD

**Issue by anaumov1** [hsafiya/My-Registry#10]
As an user I can 
Create
Read
Update
and Delete
my profile.

**Comment by vitokwolf** [comment]
- Added User Model
- Added User Api Routes for:
      - view all users,
      - view single user by ID,
      - add new user,
      - edit user information by ID,
      - delete an user by ID

**Comment by vitokwolf** [comment]
Update: 
Edit single user Api route to retrieve all registries owned by that user
