### ISSUE TITLE
Create and manipulate registries

### ISSUE THREAD

**Issue by anaumov1** [hsafiya/My-Registry#12]
As an user i can create, read , update, delete my registry.
I can retreive all my registries, 
I can retreive my registry by ID.
I can add to the registry
I can rename the registry.

**Comment by vitokwolf** [comment]
- Added Category Model (default project setup will have 4: wedding, baby-shower, birthday, xmas)
- Added categories Api routes for:
        - view all categories,
        - view single category,
        - add category,
        - edit category,
        - delete category.
PS: Category routes will be used by server/website admin, or a later implementation of "create your custom registry" option. The registries will connect to the users through categories.

**Comment by vitokwolf** [comment]
- Added Registry Model
- Created Model association 
- Added registry Api routes for:
        - view all registries, including its owner, category and items
        - view single registry, including its owner, category and items
        - add registry,
        - delete registry
 PS: do we need update route for registries? that would just update the name of it.

**Comment by vitokwolf** [comment]
Done!
