### ISSUE TITLE
Manipulations in a registry as a guest

### ISSUE THREAD

**Issue by anaumov1** [hsafiya/My-Registry#15]
As a guest I can view all registries
As a guest i can view registries by category
As a guest I can view registry by ID
As a guest when i click on "Buy" - im directed to the login page or sign up page

**Comment by anaumov1** [comment]
As a guest I can view all registries
As a guest i can view registries by category
As a guest I can view registry by ID
As a guest when i click on "Buy" - im directed to the login page or sign up page

**Comment by vitokwolf** [comment]
I think we should restrict guests viewing contents of a registry, so i'll close this.
