### ISSUE TITLE
Add "Registry" page

### ISSUE THREAD

**Issue by anaumov1** [hsafiya/My-Registry#18]
* Page should contain 
         - add item
         - delete item
         - publish registry
         - more buttons if needed
* when add item is clicked, a new item line is added with fields for:
         - line item name
         - line item link   (Alex to research option to buy straight from our site without going to OP site) - for MVP just the option to follow link (needs to open in a new page).
* when delete item is clicked, a checkbox appears next to the line and another delete button (confirm delete)
* when a checkmark is chosen and confirm delete is pressed, that item line is deleted
* when publish button is clicked, the current registry becomes visible in the "View All Registries" (i think to do this, will add a new property to Registry Model, like is_published, and give it a boolean value)

**Comment by irynashulim** [comment]
added buttons and modal

**Comment by vitokwolf** [comment]
need to add publish button

**Comment by irynashulim** [comment]
need to add publish button - added button

**Comment by vitokwolf** [comment]
Done
