### ISSUE TITLE
Create "View all registries" page

### ISSUE THREAD

**Issue by irynashulim** [hsafiya/My-Registry#26]
* when clicked on "View registries" on the mane page - fetch - getAllRegistries API and redirect to view registries page
* on the view registries page:
          * on the top input field with "Find Registry" button
          *  Find Registry using registry_title
          *  under it  - list of all registries as buttons

* When click on a registry, check if logged in
          - if logged in, open that registry by redirecting to that registry page
          - if not logged in, redirect to login page

**Comment by hsafiya** [comment]
completed
