### ISSUE TITLE
Add "Create Registry" page

### ISSUE THREAD

**Issue by vitokwolf** [hsafiya/My-Registry#41]
* When page is opened, a form is present. The form should have input fields for: 
         - registry name
         - address
         - submit button
 * when submit is clicked, then we are redirected to "Registry" page, with the name from input and the information is stored in that Registry object

**Comment by irynashulim** [comment]
When page is opened, a form is present. The form should have input fields for:
- registry name
- address
- submit button - done this part

**Comment by vitokwolf** [comment]
This is Done!
